name: Push & PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  validate:
    uses: ./.github/workflows/validate.yml
  test:
    uses: ./.github/workflows/test.yml
