name: Test

on:
  workflow_call:
  workflow_dispatch:
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        activesupport: ['6.1', '7.0']
        ruby: ['2.7', '3.0']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: ${{ matrix.activesupport }}
      env:
        ACTIVESUPPORT: ${{ matrix.activesupport }}
    - name: Rspec
      run: bundle exec rspec
